### PR TITLE
Added Blizzard.j/common.j autocomplete

### PR DESCRIPTION
**Pull request by Gismo359**
Contains autocompletion for
1163 common.j natives, including arguments,
425 common.j constants
925 Blizzard.j functions, including arguments
304 Blizzard.j constants
Preview:
example

### CODE REVIEW

**Comment by Cokemonkey11** [comment]
I tried following my own installation instructions and this doesn't seem to do anything.

Can you add some context? How do I enable this?

**Comment by Gismo359** [comment]
It should be enabled by default. Try pressing Tab or CTRL + Space to manually show it.

I just put it in the same folder as yours. I didnt try it in a .sublime-package file though.

It was made for ST2 so it may not work when packaged like that. Ill see do a bit more research and see what I can do when Im on a PC.

E: From what I could understand it has to be in json and renamed something like wurst.sublime-autocomplete. Luckily, the format isnt much different.  Ill check if that works tommorrow. Also, not being able to edit posts in mobile mode is a pain.

**Comment by Gismo359** [comment]
Actualy, the current one works just fine. What I noticed is that a sublime package only works if it is in the installed packages folder, not in packages. Also, I never really played around with show_popup(). I may be able to add some fancy tooltips.

E: Well, well after some tinkering with show_popup() I managed to make this:
example1

The colors in the popup are put manually, not from the color scheme, at the moment. Maybe I should make it so it autocompletes only the function name itself, and the arguments like this. Sort of like TESH does it.
The popup can also be attacked to the autocomplete window itself, but I dont think there is a way to see which item is selected, so it becomes kind of pointless.
At the moment, I've put only a handfull of functions/natives, so I'll have to see how it does with all of them, and most importantly how to actually get them there.

**Comment by Cokemonkey11** [comment]
Hi,

Thanks for looking more into this. You mentioned a few things about renaming the file to make it work. Can you make a new commit that does exactly what I need to get this to work?

Keep in mind the extent of my knowledge of sublime packages is all written right here: https://github.com/Cokemonkey11/wurst-sublime/blob/master/readme.md

Anything else will need to be spelled out for me.

Also, note that this package already has syntax highlighting for common.j - I left out blizzard.j and 99% of the ai natives.

And note as well that this is for _wurst_, which there is a standard library for.

Thanks again.

**Comment by Gismo359** [comment]
The installation instructions are the ones recommended for installing a user-made package, like this one.
Placing the wurst_completions.py in the Wurst.sublime-package will enable it, as long as you have autocompletion enabled in your settings. I've tested this on 2 computers, both on Windows 7. The thing about renaming was just a quick search on the internet from my phone because I wasnt on a computer to test it.

Try using autocompletion from another language and see if it works, for example, in HTML type '<a' then press Tab and it should be completed to '<a href=""></a>'.

Well, you can still use Blizzard.j functions/constants and common.j natives/constants in Wurst, so it wouldnt hurt having them, IMO. I can also give you a list of all Blizzard.j functions/constants for highlighting if you want. No AI functions/natives/constants are included here, although I probably should add the more usefull ones, like UnitAlive and the ones for gold/lumber cost. Also, no fancy tooltips yet.

I may give a try at adding support for the standard library, atleast some part of it. Not exatcly sure of the format though, as JASS2 doesnt have classes it was kind of straight forward.

E:Woops, closed on accident.

**Comment by Cokemonkey11** [comment]
I'm not sure what changed, but I got it to work by just re-zipping it and copying it in.

I don't see any reason not to include this, since people can simply not zip it up if they don't want access to it.

It would be nice I could somehow disable the BJ functions.

Accepted.

**Pull request merged**
