### PR TITLE
Updated auto-completion

### PR DESCRIPTION
**Pull request by Gismo359**
Arguments are no longer auto-completed automatically, instead a tooltip pops up when you open parentheses(ST3 only).
The tooltips contain the same color scheme as the default in WurstWE.

example

Contains settings for auto-completion:

<table>
<td>
    //Complete Blizzard.j functions and constants<br>
    //Default: true<br>
    "complete_blizzard_j": true,<br>
    //Complete common.j natives and constants<br>
    //Default: true<br>
    "complete_common_j": true,<br>
    //Display Blizzard.j functions' arguments/contents<br>
    //Default: true<br>
    "popup_blizzard_j": true,<br>
    //Display common.j natives' arguments<br>
    //Default: true<br>
    "popup_common_j": true<br>
</table>

(code tags werent working normally)

I <i>could</i> make it use the colors from the current scheme but that would require using an external dependency.
Dependencies are installed automatically by package control so I may give it a try.It is still early development though.

### CODE REVIEW

**Comment by Cokemonkey11** [comment]
@Gismo3590 sorry for the long awaited response.

In general this all looks good. I've installed sublime text 3 and verified that this is working as expected.

I have a number of points for your consideration that can be split in two categories:
- Issues that must be resolved before I can merge this
- Issues that I will ignore for now, but will be problems in future pull requests if not addressed

Some of these issues I will include here, and some will be comments within your commits.

**Comment by Cokemonkey11** [comment]
Preserving history metadata:

You've developed these changes on your own `master` branch, and force merged the upstream (my `master` branch) onto your working copy. This created [this commit](https://github.com/Gismo3590/wurst-sublime/commit/2f0bc1e2b1b9f99b6a209cf0754e8030c93578ae)

You need to fix this before I can merge your changes. In general you need to:
- Revert the merge commit (`git checkout 48da498573cce76546d792791f869834fd30a387`)
- Checkout a new branch (`git checkout -b reverting_merge`)
- Force pull the upstream onto your master branch:
  - `git fetch upstream`
  - `git checkout upstream/master`
  - `git branch -D master`
  - `git checkout -b master`
- Re-configure the master to target your origin, and force-push it to your origin:
  - `git checkout reverting_merge`
  - `git push -u origin reverting_merge`
  - `git checkout master`
  - `git push -f origin master:master`
  - `git push -u origin master`
- Rebase your reverted version onto the upstream, preserving metadata:
  - `git checkout reverting_merge`
  - `git rebase master`
  - `git push`
- Make a new pull request with this fixed branch.

However, if you're new to git this will be very painful. _This time_ we can do something easier, and simply squash all your commits (including the accidental forward merge) - http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

If you squash the commits, make sure to use a descriptive commit message.

Once more: you need to fix this issue before I will merge this pull request. If you're having problems figuring out how to do this I can help.

**Comment by Cokemonkey11** [comment]
Imperative Mood

All of your commits here use the wrong _writing mood_ for consistent history data. In future, can you please use the _imperative mood_?

See: http://chris.beams.io/posts/git-commit/#imperative

**Comment by Cokemonkey11** [comment]
@Gismo3590 Any progress?

**Comment by Gismo359** [comment]
I havent had much time the past week, sadly.I will try and do it tommorrow.

**Comment by Cokemonkey11** [comment]
No worries, no rush.

**Comment by Cokemonkey11** [comment]
@Gismo3590 any progress on this?

**Comment by Cokemonkey11** [comment]
Closing as inactive. Feel free to make a new PR if you get back into this.

**Pull request closed without merging**
